### ISSUE TITLE
organism images?

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_chado_datasets#31]
Clearly the organism image upload is happening somewhere, but where/how?

The readme says 
>create a "datasets" folder for organism image under sites/default/files/

**Comment by mpoelchau** [comment]
I do not know what that comment is about... Organism image upload happens by the admin in https://i5k.nal.usda.gov/node/add/chado-organism, and they are stored in sites/default/files

**Comment by bradfordcondon** [comment]
thanks very interesting.  Many of the forms pass around a "image upload" parameter but theres nothing in the form that would allow a user to upload an image, so I was getting a little confused.

If image upload is controlled by the admin then we can get rid of all that, and maybe create a future issue to allow user-uploaded images.

**Comment by mpoelchau** [comment]
Ah. I think we used to have a field for an image URL in a previous iteration of the form. So it's probably a relic. I think it should be safe to remove.
