### ISSUE TITLE
dataset submission view is not great

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_chado_datasets#42]
Editing a dataset (chado analysis) to confirm doesn't look styled properly to me:

from `/admin/structure/datasets/report`, edit a submission.

Heres what http://localhost:8083/datasets/1/view looks like for me:

![screen shot 2018-10-03 at 12 20 51 pm](https://user-images.githubusercontent.com/7063154/46424362-e6c1ec80-c706-11e8-847b-3d16b9ad22a5.png)

 
Is this comparable to what's live, or is there something wrong with the styling?  In this case its using the "Assembly" template, which does seem to only make use of `<p>` and `<b>` elements.

Seems to me like using standard drupal table theming would be a big improvement from this.

**Comment by mpoelchau** [comment]
Yep, that's the way it is right now. Happy to have any improvements.

**Comment by bradfordcondon** [comment]
I switched to just looping through key/value pairs and setting in a table, with a "legend" lookup array to change the machine label for a human readable one.

  More legible?  It's certainly more code-friendly since the display is no longer hard-coded.

<img width="808" alt="screen shot 2018-10-04 at 9 32 37 am" src="https://user-images.githubusercontent.com/7063154/46477340-78d5fd80-c7b8-11e8-938c-0fc7acf0923b.png">


It occurs to me that these fields should be editable by the admin to correct typos etc.  I think that will be a "next release" feature since I'm liking the "workbench style" approach more and more...
