### ISSUE TITLE
FUture TODO: only display certain organisms?

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_chado_datasets#8]
right now the module will display ALL organisms in chado.  i was thinking it should only display modules with apollo instances, but maybe not, since the point of this module is to prompt i5k to create an apollo instance for said organism!

**Comment by mpoelchau** [comment]
Yeah, it should display all organisms in chado (assuming that datasets/request-project adds the organism into chado).

**Comment by bradfordcondon** [comment]
OK, if it should display all organisms then this is a non-issue, thank you @mpoelchau !
